import React from 'react';
import { Info, Code, User, Users, GraduationCap, Server } from 'lucide-react';

export default function About() {
  return (
    <div className="flex flex-col items-center justify-center min-h-[85vh] py-12 px-4 sm:px-6 lg:px-8 relative animate-fade-in-up">
      <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[600px] h-[600px] bg-primary/10 blur-[150px] rounded-full pointer-events-none"></div>

      <div className="w-full max-w-3xl glass p-10 rounded-3xl shadow-2xl relative z-10 border border-glassBorder/50">
        <div className="text-center mb-10">
          <div className="inline-flex items-center justify-center p-4 bg-primary/10 rounded-full mb-4 border border-primary/20">
            <Info className="text-primary w-8 h-8" />
          </div>
          <h1 className="text-4xl font-black tracking-tight text-white mb-2">Project Info</h1>
          <p className="text-gray-400 font-light text-lg">Human vs AI Q&A Platform Architecture</p>
        </div>

        <div className="space-y-6">
          <div className="flex items-start gap-4 p-5 bg-dark/50 rounded-2xl border border-glassBorder hover:border-primary/30 transition-colors">
            <GraduationCap className="text-primary mt-1 flex-shrink-0" />
            <div>
              <h3 className="text-sm font-bold text-gray-500 uppercase tracking-wider mb-1">Institution</h3>
              <p className="text-white text-lg font-medium">Akdeniz University</p>
              <p className="text-gray-400">Software Engineering Course Project</p>
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div className="flex items-start gap-4 p-5 bg-dark/50 rounded-2xl border border-glassBorder hover:border-secondary/30 transition-colors">
              <User className="text-secondary mt-1 flex-shrink-0" />
              <div>
                <h3 className="text-sm font-bold text-gray-500 uppercase tracking-wider mb-1">Lead Developers</h3>
                <p className="text-white text-lg font-medium">Melih Kerem Arslan <br /> Beril Sude Çimenoğlu</p>
              </div>
            </div>

            <div className="flex items-start gap-4 p-5 bg-dark/50 rounded-2xl border border-glassBorder hover:border-secondary/30 transition-colors">
              <Users className="text-secondary mt-1 flex-shrink-0" />
              <div>
                <h3 className="text-sm font-bold text-gray-500 uppercase tracking-wider mb-1">Contributors</h3>
                <p className="text-white text-lg font-medium">Team Members</p>
              </div>
            </div>
          </div>

          <div className="flex items-start gap-4 p-5 bg-dark/50 rounded-2xl border border-glassBorder hover:border-primary/30 transition-colors">
            <Server className="text-primary mt-1 flex-shrink-0" />
            <div>
              <h3 className="text-sm font-bold text-gray-500 uppercase tracking-wider mb-1">Tech Stack</h3>
              <div className="flex flex-wrap gap-2 mt-2">
                {['React', 'Node.js', 'Express', 'SQLite', 'Gemini API', 'Socket.io', 'Tailwind CSS'].map((tech) => (
                  <span key={tech} className="px-3 py-1 bg-white/5 border border-white/10 rounded-full text-sm text-gray-300">
                    {tech}
                  </span>
                ))}
              </div>
            </div>
          </div>

          <div className="flex items-start gap-4 p-5 bg-dark/50 rounded-2xl border border-glassBorder hover:border-primary/30 transition-colors">
            <Code className="text-primary mt-1 flex-shrink-0" />
            <div>
              <h3 className="text-sm font-bold text-gray-500 uppercase tracking-wider mb-1">Description</h3>
              <p className="text-gray-300 leading-relaxed">
                A real-time, interactive game where users submit questions and attempt to guess whether the corresponding answer was written by a real Human Doctor or generated by an AI assistant. Built with complete session isolation, live websockets, and a group-based scoreboard system.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
